### ISSUE TITLE
enum SHT has no entry with code 1879048193.

### ISSUE THREAD

**Issue by komakai** [cesena/ghidra2dwarf#12]
I get the above error trying to run ghidra2dwarf against an arm android library.
1879048193 is 0x70000001 which is SHT_LOPROC + 1
The check for valid SHT values needs to be able to allow any value between
SHT_LOPROC and SHT_HIPROC
(same for SHT_LOUSER and SHT_HIUSER as well)

**Comment by lacraig2** [comment]
This is probably their limited SHT list. This is a more comprehensive list. https://github.com/osandov/drgn/blob/main/tests/elf.py
