### ISSUE TITLE
Debug section files can be deleted afterwards

### ISSUE THREAD

**Issue by io12** [cesena/ghidra2dwarf#3]
The script can delete the `.debug_info`, `.debug_line`, and `.debug_abbrev` files, so they don't clutter the binary's directory.

**Comment by NextLight** [comment]
51062f754d14928ff5585bb206fa8c611062344e fixes this issue because we don't have to create the section files at all.

Using `objcopy` and the `export.sh` script was a temporary workaround, now we are doing everything in python so we can keep the sections in memory.
