### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'long' and 'NoneType'

### ISSUE THREAD

**Issue by jy95** [cesena/ghidra2dwarf#8]
Hello,

I am using Ghidra 9.2.3 and I got an issue when testing a binary with your script : 

![image](https://user-images.githubusercontent.com/9306961/120069890-7e2e9780-c088-11eb-9dcc-baceeac71561.png)

Thanks in advance,

**Comment by meowmeowxw** [comment]
Hi, Can you share the binary?

**Comment by jy95** [comment]
@meowmeowxw I just sent you it on your protonmail mail ;)

**Comment by meowmeowxw** [comment]
Received, ghidra2dwarf only works on ELF binaries not PE
